name: Docker RPM/DEB Install and Script Execution

on:
  push:
    branches:
      - main  # Trigger pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the pipeline on Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repo

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Set up Docker Buildx (for multi-platform builds)
    
    - name: Build Docker image
      run: |
        docker build -t mydockerimage .  # Build the Docker image from the current directory

    - name: Run Docker container
      run: |
        docker run --rm --name mycontainer mydockerimage /bin/bash -c "
          # Install dependencies and package (RPM/DEB)
          if [ -f mypackage-1.0.deb ]; then
            apt update && apt install -y mypackage-1.0.deb
          elif [ -f my_script_package-1.0-1.noarch.rpm ]; then
            yum install -y my_script_package-1.0-1.noarch.rpm
          fi
          
          # Execute the script
          bash script.sh
        "
